# -*- coding: utf-8 -*-
"""Steamlit_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CrDYrI6SCEwl-_Kd9t-8RsbIizZxl91v
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st

st.title("BMI Calculator")

weight  = st.number_input("Weight(kg)")
height = st.number_input("Height(m)")

if st.button("Calculate BMI"):
  bmi=weight/(height**2)
  st.success(f"BMI:{bmi:.2f}")

  if bmi < 18.5:
    st.warning("underweight")

  elif bmi < 25:
    st.succes("Normal")

  else:
    st.error("Overweight")